services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Evently.Api
    build:
      context: .
      dockerfile: src/Evently.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
  
  evently.database:
    image: postgres:18.1-alpine3.23
    container_name: Evently.Database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  evently.identity:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: Evently.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
      - 9000:9000

  evently.seq:
    image: datalust/seq:2025.2
    container_name: Evently.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - 5341:5341
      - 8081:80

  evently.redis:
    image: redis:8.4.0
    container_name: Evently.Redis
    restart: always
    ports:
      - 6379:6379
